# Generated by Django 2.1.8 on 2020-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorhistory',
            name='bollinger_middle',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
