# Generated by Django 3.1.5 on 2021-01-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheet',
            name='reportDate',
        ),
    ]
