# Generated by Django 3.1.5 on 2021-01-31 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_balancesheet_reportdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='reportDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
