# Generated by Django 3.1.5 on 2021-01-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_balancesheet_reportdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='commonStock',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='currentAssets',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='currentCash',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='goodwill',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='intangibleAssets',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='inventory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='longTermDebt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='longTermInvestments',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='minorityInterest',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='netTangibleAssets',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='otherAssets',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='otherCurrentAssets',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='propertyPlantEquipment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='receivables',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='retainedEarnings',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='shareholderEquity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='totalAssets',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='totalCurrentLiabilities',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='totalLiabilities',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='treasuryStock',
            field=models.CharField(max_length=50),
        ),
    ]
