# Generated by Django 3.1.5 on 2021-01-31 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stock_iexfinance_ticker'),
        ('analysis', '0004_auto_20210131_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystats',
            name='marketcap',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('costOfRevenue', models.CharField(max_length=50)),
                ('ebit', models.CharField(max_length=50)),
                ('filingType', models.CharField(max_length=50)),
                ('fiscalDate', models.IntegerField()),
                ('fiscalQuarter', models.IntegerField()),
                ('fiscalYear', models.IntegerField()),
                ('grossProfit', models.CharField(max_length=50)),
                ('incomeTax', models.CharField(max_length=50)),
                ('interestIncome', models.CharField(max_length=50)),
                ('minorityInterest', models.CharField(max_length=50)),
                ('netIncome', models.CharField(max_length=50)),
                ('netIncomeBasic', models.CharField(max_length=50)),
                ('operatingExpense', models.CharField(max_length=50)),
                ('operatingIncome', models.CharField(max_length=50)),
                ('otherIncomeExpenseNet', models.CharField(max_length=50)),
                ('pretaxIncome', models.CharField(max_length=50)),
                ('reportDate', models.DateField()),
                ('researchAndDevelopment', models.CharField(max_length=50)),
                ('sellingGeneralAndAdmin', models.CharField(max_length=50)),
                ('totalRevenue', models.CharField(max_length=50)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('capitalExpenditures', models.CharField(max_length=50)),
                ('cashFlow', models.CharField(max_length=50)),
                ('cashFlowFinancing', models.CharField(max_length=50)),
                ('depreciation', models.CharField(max_length=50)),
                ('fiscalDate', models.IntegerField()),
                ('fiscalQuarter', models.IntegerField()),
                ('fiscalYear', models.IntegerField()),
                ('netIncome', models.CharField(max_length=50)),
                ('reportDate', models.DateField()),
                ('totalInvestingCashFlows', models.CharField(max_length=50)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
