# Generated by Django 3.1.5 on 2021-01-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='last_downloaded_articles',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='last_downloaded_stocks',
        ),
    ]
