# Generated by Django 2.1.15 on 2020-10-20 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('to_eur', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ticker', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, unique=True)),
                ('article_ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('downloading_stock_data', models.BooleanField(default=False)),
                ('downloading_article_data', models.BooleanField(default=False)),
                ('n_articles_avg', models.IntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.CurrencyTicker')),
            ],
        ),
        migrations.CreateModel(
            name='Stockkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('o', models.FloatField(null=True)),
                ('l', models.FloatField(null=True)),
                ('h', models.FloatField(null=True)),
                ('c', models.FloatField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=1000, null=True)),
                ('combined', models.BooleanField(default=False)),
                ('is_split', models.BooleanField(default=False)),
                ('date_bought', models.DateField()),
                ('price_bought', models.FloatField(blank=True, null=True)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('price_sold', models.FloatField(blank=True, null=True)),
                ('buy_fees', models.FloatField(blank=True)),
                ('buy_fees_constant', models.FloatField(blank=True, default=0)),
                ('buy_fees_linear', models.FloatField(blank=True, default=0)),
                ('sell_fees', models.FloatField(blank=True)),
                ('sell_fees_constant', models.FloatField(blank=True, default=0)),
                ('sell_fees_linear', models.FloatField(blank=True, default=0)),
                ('lower_alert', models.FloatField(blank=True, null=True)),
                ('upper_alert', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortfolioHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('profit', models.FloatField()),
                ('invested', models.FloatField()),
                ('net', models.FloatField()),
                ('cash', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.CurrencyTicker'),
        ),
    ]
