# Generated by Django 2.1.8 on 2020-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricehistory',
            name='v',
            field=models.FloatField(null=True),
        ),
    ]
