# Generated by Django 2.1.8 on 2020-12-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stockpricehistory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='downloading_article_data',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='downloading_stock_data',
        ),
    ]
