# Generated by Django 3.1.5 on 2021-01-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20201209_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['name']},
        ),
    ]
