# Generated by Django 3.1.5 on 2021-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_transaction_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.CharField(default='Portfolio', max_length=100),
        ),
    ]
