# Generated by Django 3.1.5 on 2021-01-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20210124_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='portfolio',
            field=models.CharField(blank=True, default='Portfolio', max_length=100),
        ),
    ]
