# Generated by Django 3.1.5 on 2021-01-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20210128_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='iexfinance_ticker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
